info:
  name: micro-rest
  version: 0.0.0
  description: Boilerplate for REST Microservice in Java
  documentation: https://github.com/javaboilerplates/micro-rest
server:
  port: 8000
spring:
  boot:
    admin:
      url: http://localhost:8002
      username: admin
      password: admin
  application:
    name: ${info.name}
management:
  security:
    enabled: false


